export const blogYazilari = [
  {
    slug: "bursa-avm-magaza-led-ekran",
    title: "Bursa AVM Mağaza LED Ekran Uygulaması: Siyane Scarf Projesi",
    excerpt: "Bursa alışveriş merkezinde Siyane Scarf eşarp mağazası için gerçekleştirdiğimiz LED ekran projesi. Bursa LED ekran montaj ve profesyonel LED ekran kiralama için Lederkon.",
    date: "2026-02-28",
    image: "/images/gallery/Siyane Scarf Led Ekran.jpeg",
  },
  {
    slug: "led-ekran-fiyatlari-2026",
    title: "LED Ekran Fiyatları 2026",
    excerpt: "2026 yılında LED ekran fiyatları nasıl şekilleniyor? Pixel pitch, metrekare ve kullanım alanına göre güncel fiyat rehberi.",
    date: "2026-02-01",
    image: "/images/products/LED video wall modular panel.webp",
  },
  {
    slug: "indoor-ve-outdoor-led-farki",
    title: "Indoor ve Outdoor LED Farkı",
    excerpt: "Kapalı alan (indoor) ve açık hava (outdoor) LED ekranlar arasındaki teknik ve maliyet farkları.",
    date: "2026-01-28",
    image: "/images/products/Outdoor LED cabinet back side.jpg",
  },
  {
    slug: "pixel-pitch-nedir",
    title: "Pixel Pitch Nedir?",
    excerpt: "LED ekranlarda pixel pitch (nokta aralığı) ne anlama gelir, nasıl seçilir ve LED ekran fiyatlarını nasıl etkiler?",
    date: "2026-01-25",
    image: "/images/products/Indoor LED panel close up.jpg",
  },
  {
    slug: "dugun-salonu-led-ekran-secimi",
    title: "Düğün Salonu LED Ekran Seçimi",
    excerpt: "Düğün salonu için LED ekran seçerken dikkat edilmesi gerekenler: boyut, pixel pitch ve kiralama vs sabit montaj.",
    date: "2026-01-20",
    image: "/images/gallery/wedding-1.webp",
  },
  {
    slug: "cami-led-ekran-sistemleri",
    title: "Cami LED Ekran Sistemleri",
    excerpt: "Cami ve ibadethaneler için LED ekran: vaaz, hutbe ve bilgilendirme ekranı teknik özellikleri ve montaj.",
    date: "2026-01-15",
    image: "/images/gallery/cami-1.jpg",
  },
  {
    slug: "avm-icin-led-ekran-cozumleri",
    title: "AVM İçin LED Ekran Çözümleri",
    excerpt: "Alışveriş merkezlerinde iç ve dış mekân LED ekran uygulamaları, reklam ve bilgilendirme sistemleri.",
    date: "2026-01-10",
    image: "/images/gallery/mall-1.png",
  },
  {
    slug: "led-ekran-m2-fiyati",
    title: "LED Ekran m² Fiyatı 2026",
    excerpt: "Metrekareye göre LED ekran fiyatları. m² birim fiyatı hesaplama, pixel pitch ve kullanım alanına göre güncel rehber.",
    date: "2026-02-18",
    image: "/images/products/Indoor LED panel close up.jpg",
  },
  {
    slug: "led-ekran-kiralama-rehberi",
    title: "LED Ekran Kiralama Rehberi",
    excerpt: "Etkinlik ve düğün için LED ekran kiralama: süre, boyut, kurulum ve fiyatlandırma. Kiralama mı satın almak mı?",
    date: "2026-02-17",
    image: "/images/solutions/kiralik-led-ekran.webp",
  },
  {
    slug: "led-ekran-kiralama-fiyatlari",
    title: "LED Ekran Kiralama Fiyatları",
    excerpt: "Güncel LED ekran kiralama fiyatları. Günlük ve haftalık kiralama seçenekleri, ekran boyutuna göre fiyat aralıkları.",
    date: "2026-02-16",
    image: "/images/gallery/led-screen-1.webp",
  },
  {
    slug: "led-panel-fiyatlari",
    title: "LED Panel Fiyatları ve Modül Seçimi",
    excerpt: "LED panel ve modül fiyatları. Video wall, indoor ve outdoor LED panel çeşitleri, kalite ve fiyat karşılaştırması.",
    date: "2026-02-15",
    image: "/images/products/LED video wall modular panel.webp",
  },
  {
    slug: "led-ekran-imalati-turkiye",
    title: "LED Ekran İmalatı Türkiye",
    excerpt: "Türkiye'de LED ekran imalatı, yerli üretim ve ithal modüller. Kalite, garanti ve montaj hizmeti sunan firmalar.",
    date: "2026-02-14",
    image: "/images/products/Outdoor LED cabinet back side.jpg",
  },
  {
    slug: "led-ekran-montaj-sureci",
    title: "LED Ekran Montaj Süreci ve Aşamaları",
    excerpt: "LED ekran montajı nasıl yapılır? Keşif, proje, kurulum ve devreye alma. Profesyonel LED ekran montaj firması.",
    date: "2026-02-13",
    image: "/images/gallery/led-screen-2.jpg",
  },
  {
    slug: "led-reklam-ekrani-secimi",
    title: "LED Reklam Ekranı Seçimi ve Fiyatları",
    excerpt: "Mağaza, cephe ve açık hava için LED reklam ekranı. Boyut, parlaklık ve içerik yönetimi rehberi.",
    date: "2026-02-12",
    image: "/images/solutions/led-reklam-ekrani.webp",
  },
  {
    slug: "led-billboard-reklam",
    title: "LED Billboard Reklam ve Dış Mekân Ekranları",
    excerpt: "Billboard ve dış cephe LED ekranları. Reklam geliri, parlaklık, IP koruma ve proje maliyetleri.",
    date: "2026-02-11",
    image: "/images/gallery/billboard-1.webp",
  },
  {
    slug: "led-video-wall",
    title: "LED Video Wall Nedir? Kurulum ve Fiyat",
    excerpt: "Video wall (videowall) LED ekran sistemleri. Kontrol odası, showroom ve kurumsal uygulamalar için çözümler.",
    date: "2026-02-10",
    image: "/images/products/LED video wall modular panel.webp",
  },
  {
    slug: "cephe-led-ekran",
    title: "Cephe LED Ekran Uygulamaları",
    excerpt: "Bina cephesi ve vitrin LED ekran. Şeffaf ve sabit cephe ekranları, reklam ve mimari aydınlatma.",
    date: "2026-02-09",
    image: "/images/solutions/dis-mekan-led-ekran.webp",
  },
  {
    slug: "sahne-led-ekran",
    title: "Sahne LED Ekran ve Etkinlik Çözümleri",
    excerpt: "Konser, konferans ve sahne için LED ekran kiralama. P3, P4 sahne ekranları ve teknik gereksinimler.",
    date: "2026-02-08",
    image: "/images/gallery/led-screen-1.webp",
  },
  {
    slug: "mobil-led-ekran-kiralama",
    title: "Mobil LED Ekran Kiralama",
    excerpt: "Seyyar ve mobil LED ekran kiralama. Araç üstü, trailer ve taşınabilir LED ekran fiyatları ve kullanım alanları.",
    date: "2026-02-07",
    image: "/images/product-list/rental-screen.webp",
  },
  {
    slug: "fuar-led-ekran-kiralama",
    title: "Fuar LED Ekran Kiralama",
    excerpt: "Fuar, sergi ve etkinlikler için LED ekran kiralama. Stand görünürlüğü, kurulum ve fiyatlar. Lederkon fuar LED ekran hizmeti.",
    date: "2026-02-20",
    image: "/images/solutions/kiralik-led-ekran.webp",
  },
  {
    slug: "magaza-vitrin-led-ekran",
    title: "Mağaza Vitrin LED Ekran",
    excerpt: "Mağaza vitrini ve perakende için LED ekran. Cam arkası, şeffaf ve sabit vitrin LED ekran çözümleri ve fiyatları.",
    date: "2026-02-19",
    image: "/images/solutions/led-reklam-ekrani.webp",
  },
  {
    slug: "cam-arkasi-led-ekran",
    title: "Cam Arkası ve Cam Cephe LED Ekran",
    excerpt: "Cam arkası LED ekran, vitrin ve cephe uygulamaları. Şeffaf LED ekran nedir, fiyatları ve kullanım alanları.",
    date: "2026-02-18",
    image: "/images/product-list/Transparent-LED-Screen.jpg",
  },
  {
    slug: "otel-led-ekran-cozumleri",
    title: "Otel LED Ekran Çözümleri",
    excerpt: "Otel lobi, resepsiyon ve kongre salonu için LED ekran. Bilgilendirme, reklam ve etkinlik ekranları. Lederkon otel projeleri.",
    date: "2026-02-17",
    image: "/images/gallery/mall-1.png",
  },
  {
    slug: "belediye-led-ekran-sistemi",
    title: "Belediye LED Ekran Sistemi",
    excerpt: "Belediye meydan, durak ve bina cephesi LED ekran. Duyuru, bilgilendirme ve acil durum ekranları. Kamu LED ekran projeleri.",
    date: "2026-02-16",
    image: "/images/solutions/dis-mekan-led-ekran.webp",
  },
  {
    slug: "okul-icin-led-ekran",
    title: "Okul İçin LED Ekran",
    excerpt: "Okul, üniversite ve eğitim kurumları için LED ekran. Salon, koridor ve dış cephe duyuru ekranları. Eğitim LED ekran çözümleri.",
    date: "2026-02-15",
    image: "/images/products/Indoor LED panel close up.jpg",
  },
  {
    slug: "dugun-salonu-led-ekran-fiyati",
    title: "Düğün Salonu LED Ekran Fiyatı",
    excerpt: "Düğün salonu LED ekran fiyatları: kiralama ve sabit montaj. m² ve günlük fiyat aralıkları. Lederkon düğün LED ekran teklifi.",
    date: "2026-02-14",
    image: "/images/gallery/wedding-1.webp",
  },
  {
    slug: "p25-led-panel-nedir",
    title: "P2.5 LED Panel Nedir?",
    excerpt: "P2.5 pixel pitch LED panel özellikleri, kullanım alanları ve fiyatları. Yakın mesafe izleme için P2.5 LED ekran rehberi.",
    date: "2026-02-13",
    image: "/images/products/Indoor LED panel close up.jpg",
  },
  {
    slug: "p3-led-ekran-nedir",
    title: "P3 LED Ekran Nedir?",
    excerpt: "P3 led ekran ne demek? Pixel pitch 3 mm LED ekran kullanım alanları, parlaklık ve fiyat. P3 indoor ve sahne ekranları.",
    date: "2026-02-12",
    image: "/images/products/LED video wall modular panel.webp",
  },
  {
    slug: "p5-outdoor-led-ekran",
    title: "P5 Outdoor LED Ekran",
    excerpt: "P5 açık hava LED ekran özellikleri ve fiyatları. Billboard, cephe ve dış mekân P5 LED ekran projeleri.",
    date: "2026-02-11",
    image: "/images/products/Outdoor LED cabinet back side.jpg",
  },
  {
    slug: "p10-led-ekran-fiyat",
    title: "P10 LED Ekran Fiyat ve Kullanım",
    excerpt: "P10 led ekran fiyat aralıkları ve kullanım alanları. Uzak mesafe reklam ve billboard için P10 LED ekran.",
    date: "2026-02-10",
    image: "/images/gallery/billboard-1.webp",
  },
  {
    slug: "smd-led-panel",
    title: "SMD LED Panel Nedir?",
    excerpt: "SMD led panel ve DIP LED farkı. SMD LED ekran avantajları, ömür ve görüntü kalitesi. Teknik alıcı rehberi.",
    date: "2026-02-09",
    image: "/images/products/Indoor LED panel close up.jpg",
  },
  {
    slug: "dip-led-ekran",
    title: "DIP LED Ekran Nedir?",
    excerpt: "DIP led ekran özellikleri, SMD ile farkı. Outdoor ve yüksek parlaklık uygulamalarında DIP LED kullanımı.",
    date: "2026-02-08",
    image: "/images/products/Outdoor LED cabinet back side.jpg",
  },
  {
    slug: "cabinet-led-panel",
    title: "Cabinet LED Panel ve Kabinet Yapısı",
    excerpt: "Cabinet led panel nedir? LED ekran kabinet tipleri, indoor/outdoor cabinet farkı ve montaj. Teknik rehber.",
    date: "2026-02-07",
    image: "/images/products/Outdoor LED cabinet back side.jpg",
  },
  {
    slug: "modul-led-ekran",
    title: "Modül LED Ekran ve Modüler Yapı",
    excerpt: "Modül led ekran nasıl çalışır? LED modül boyutları, çözünürlük ve video wall. Modüler LED ekran avantajları.",
    date: "2026-02-06",
    image: "/images/products/LED video wall modular panel.webp",
  },
  {
    slug: "led-ekran-cozunurluk-hesaplama",
    title: "LED Ekran Çözünürlük Hesaplama",
    excerpt: "LED ekran çözünürlük hesaplama: pixel pitch, boyut ve piksel sayısı. Doğru çözünürlük seçimi rehberi.",
    date: "2026-02-05",
    image: "/images/products/Indoor LED panel close up.jpg",
  },
  {
    slug: "led-ekran-metrekare-hesaplama",
    title: "LED Ekran Metrekare Hesaplama",
    excerpt: "LED ekran metrekare hesaplama: modül sayısı, izleme mesafesi ve ekran boyutu. Proje planlama rehberi.",
    date: "2026-02-04",
    image: "/images/products/LED video wall modular panel.webp",
  },
  {
    slug: "led-ekran-guc-tuketimi",
    title: "LED Ekran Güç Tüketimi",
    excerpt: "LED ekran güç tüketimi ve elektrik maliyeti. Watt/m², parlaklık ayarı ve enerji tasarrufu. Teknik bilgi.",
    date: "2026-02-03",
    image: "/images/gallery/led-screen-2.jpg",
  },
  {
    slug: "led-ekran-teknik-ozellikleri",
    title: "LED Ekran Teknik Özellikleri",
    excerpt: "LED ekran teknik özellikleri: pixel pitch, parlaklık, IP, kontrast. Satın alma öncesi bilmeniz gerekenler.",
    date: "2026-02-02",
    image: "/images/products/Indoor LED panel close up.jpg",
  },
  {
    slug: "etkinlik-led-ekran-kiralama",
    title: "Etkinlik LED Ekran Kiralama",
    excerpt: "Etkinlik, organizasyon ve özel günler için LED ekran kiralama. Kurulum, içerik ve fiyat. Lederkon etkinlik ekranı.",
    date: "2026-02-01",
    image: "/images/gallery/led-screen-1.webp",
  },
  {
    slug: "acik-hava-led-ekran-kiralama",
    title: "Açık Hava LED Ekran Kiralama",
    excerpt: "Açık hava LED ekran kiralama: festival, miting, konser. Outdoor kiralık LED ekran fiyatları ve teknik gereksinimler.",
    date: "2026-01-30",
    image: "/images/gallery/billboard-1.webp",
  },
  {
    slug: "miting-led-ekran-kiralama",
    title: "Miting LED Ekran Kiralama",
    excerpt: "Miting, açılış ve kampanya için LED ekran kiralama. Büyük format açık hava ekranı. Lederkon miting ekranı hizmeti.",
    date: "2026-01-29",
    image: "/images/product-list/rental-screen.webp",
  },
];

export function getBlogBySlug(slug) {
  return blogYazilari.find((y) => y.slug === slug);
}

export function getAllBlogSlugs() {
  return blogYazilari.map((y) => y.slug);
}
