/**
 * Galeri sayfasında listelenecek tüm görseller.
 * SEO için her öğede title ve description kullanılır (alt, hover, schema).
 */
export const galeriGorselleri = [
  { src: "/images/gallery/wedding-1.webp", title: "Düğün Salonu LED Ekran", description: "Nikah ve kına organizasyonları için profesyonel düğün salonu LED ekran kurulumu." },
  { src: "/images/gallery/wedding-2.jpg", title: "Düğün Salonu LED Ekran Uygulaması", description: "Düğün ve özel günler için LED ekran montajı ve kiralama." },
  { src: "/images/gallery/wedding-3.png", title: "Düğün Salonu LED Ekran Projesi", description: "Büyük ekranlı düğün salonu LED ekran çözümü." },
  { src: "/images/gallery/wedding-4.png", title: "Etkinlik LED Ekranı", description: "Düğün ve etkinlikler için yüksek çözünürlüklü LED ekran." },
  { src: "/images/gallery/wedding-5.jpg", title: "Nikah ve Kına LED Ekran", description: "Düğün salonu nikah ve kına gecesi LED ekran uygulaması." },
  { src: "/images/gallery/wedding-6.webp", title: "Düğün Salonu Video Duvar", description: "Düğün organizasyonları için LED video duvar kurulumu." },
  { src: "/images/gallery/wedding-7.jpg", title: "Düğün LED Ekran Montajı", description: "Profesyonel düğün salonu LED ekran montaj ve devreye alma." },
  { src: "/images/gallery/mall-1.png", title: "AVM İç Mekan LED Ekran", description: "Alışveriş merkezi iç meydan ve koridor LED ekran projesi." },
  { src: "/images/gallery/mall-2.jpg", title: "AVM LED Reklam Ekranı", description: "AVM reklam ve bilgilendirme LED ekran uygulaması." },
  { src: "/images/gallery/mall-3.jpg", title: "AVM Dijital Ekran", description: "Alışveriş merkezi dijital reklam ekranı kurulumu." },
  { src: "/images/gallery/cami-1.jpg", title: "Cami LED Ekran", description: "Cami ve ibadethaneler için vaaz, vakit ve bilgi ekranı." },
  { src: "/images/gallery/store-1.jpg", title: "Mağaza Vitrin LED Ekran", description: "Mağaza vitrini ve showroom LED ekran uygulaması." },
  { src: "/images/gallery/store-2.jpg", title: "Mağaza LED Ekran Montajı", description: "Butik ve mağaza için LED ekran çözümleri." },
  { src: "/images/gallery/store-3.jpeg", title: "Vitrin LED Ekran Projesi", description: "Mağaza vitrininde dijital LED ekran kurulumu." },
  { src: "/images/gallery/billboard-1.webp", title: "Outdoor Billboard LED Ekran", description: "Açık hava reklam panosu ve billboard LED ekran projesi." },
  { src: "/images/gallery/led-screen-1.webp", title: "LED Video Duvar", description: "Indoor LED video duvar ve modüler ekran kurulumu." },
  { src: "/images/gallery/led-screen-2.jpg", title: "LED Ekran Uygulaması", description: "Kurumsal LED ekran ve video duvar projesi." },
  { src: "/images/gallery/market-led-ekran.jpeg", title: "Market LED Bilgi Ekranı", description: "Market ve süpermarket bilgi, indirim ekranı LED montajı." },
  { src: "/images/gallery/market-led-ekran-2.jpeg", title: "Market Bilgi ve İndirim Ekranları", description: "Market içi bilgilendirme ve kampanya LED ekranları." },
  { src: "/images/products/Indoor LED panel close up.jpg", title: "Indoor LED Panel", description: "Kapalı mekân indoor LED ekran paneli ve montaj." },
  { src: "/images/products/Outdoor LED cabinet back side.jpg", title: "Outdoor LED Kabinet", description: "Açık hava outdoor LED ekran kabineti, IP65 dayanıklı yapı." },
  { src: "/images/products/LED video wall modular panel.webp", title: "LED Video Duvar Modül", description: "Modüler LED video duvar paneli, indoor kurulum." },
  { src: "/images/products/LED poster display.webp", title: "LED Poster ve Totem Ekran", description: "Totem ve poster tipi LED bilgi ekranı." },
  { src: "/images/products/Transparent LED screen.webp", title: "Şeffaf LED Ekran", description: "Vitrin ve cam uygulamaları için şeffaf LED ekran." },
  { src: "/images/products/totem-led-screen.webp", title: "Totem LED Ekran", description: "AVM ve kurumsal mekân totem LED ekran çözümü." },
  { src: "/images/product-list/indoor-led-screen.jpeg", title: "Indoor LED Ekran", description: "Kapalı mekân yüksek çözünürlüklü LED ekran." },
  { src: "/images/product-list/outdoor-led-screen.webp", title: "Outdoor LED Ekran", description: "Açık hava, reklam panosu için dayanıklı LED ekran." },
  { src: "/images/product-list/Wedding-LED-Screen.webp", title: "Düğün Salonu LED Ekran", description: "Düğün ve etkinlik LED ekran kiralama ve montaj." },
  { src: "/images/product-list/Shopping-Mall-LED-Display.jpg", title: "AVM LED Ekran", description: "Alışveriş merkezi LED reklam ve bilgilendirme ekranı." },
  { src: "/images/product-list/LED-display-screens-in-mosques.jpg", title: "Cami LED Ekran", description: "Cami vaaz ve bilgi ekranı LED çözümleri." },
  { src: "/images/product-list/totem-led-screen.jpg", title: "Totem Bilgi Ekranı", description: "Yönlendirme ve bilgilendirme totem LED ekranı." },
  { src: "/images/product-list/Transparent-LED-Screen.jpg", title: "Şeffaf LED Ekran Vitrin", description: "Vitrin ve showroom şeffaf LED ekran uygulaması." },
  { src: "/images/product-list/flexible-led-display-screen.webp", title: "Esnek LED Ekran", description: "Kavisli ve özel formatta esnek LED ekran." },
  { src: "/images/product-list/rental-screen.webp", title: "Kiralık Rental LED Ekran", description: "Konser, fuar ve etkinlikler için kiralık LED ekran." },
  { src: "/images/product-list/LED-flexible-screen.jpg", title: "Esnek LED Ekran Uygulaması", description: "Eğilebilir LED ekran, kavisli yüzey kurulumu." },
  { src: "/images/hero/lederkon-1.png", title: "Lederkon LED Ekran Projesi", description: "Profesyonel LED ekran montaj ve proje çözümleri." },
  { src: "/images/hero/lederkon-2.png", title: "Lederkon Kurumsal LED Ekran", description: "Türkiye geneli LED ekran tedarik ve montaj." },
  { src: "/images/hero/lederkon-3.jpeg", title: "LED Ekran Kurulumu", description: "LED ekran montaj, devreye alma ve teknik destek." },
  { src: "/images/hero/lederkon-4.jpeg", title: "Lederkon Referans Proje", description: "Indoor ve outdoor LED ekran referans uygulaması." },
  { src: "/images/hero/lederkon-5.jpeg", title: "LED Ekran Montaj Firması", description: "Lederkon LED ekran montaj ve proje hizmeti." },
  { src: "/images/hero/lederkon-6.jpeg", title: "LED Ekran Çözümleri", description: "Düğün salonu, cami, AVM LED ekran çözümleri." },
];
