export const projeler = [
  {
    id: 1,
    title: "Lüks Düğün Salonu LED Ekran",
    description: "40 m² düğün salonu LED ekran montajı. Nikah ve kına organizasyonları için sabit kurulum.",
    category: "dugun",
    image: "/images/gallery/wedding-1.webp",
  },
  {
    id: 2,
    title: "AVM İç Meydan Dev Ekran",
    description: "Alışveriş merkezi iç meydanında 25 m² indoor LED ekran projesi.",
    category: "avm",
    image: "/images/gallery/mall-1.png",
  },
  {
    id: 4,
    title: "Mağaza Vitrin LED",
    description: "Butik mağaza vitrininde şerit LED ekran ve dijital poster uygulaması.",
    category: "magaza",
    image: "/images/gallery/store-1.jpg",
  },
  {
    id: 5,
    title: "Cadde Billboard LED Ekran",
    description: "Şehir merkezinde 30 m² outdoor reklam panosu. IP65, yüksek parlaklık.",
    category: "billboard",
    image: "/images/gallery/billboard-1.webp",
  },
  {
    id: 6,
    title: "Düğün Salonu Kiralık Ekran",
    description: "Kına gecesi için 15 m² kiralık LED ekran ve operatör hizmeti.",
    category: "dugun",
    image: "/images/gallery/wedding-2.jpg",
  },
  {
    id: 7,
    title: "AVM Dış Cephe Reklam Ekranı",
    description: "AVM dış cephede 50 m² outdoor LED ekran. Merkezi reklam yönetimi.",
    category: "avm",
    image: "/images/gallery/mall-2.jpg",
  },
  {
    id: 8,
    title: "Cami Bilgi ve Vakit Ekranı",
    description: "Cami girişinde namaz vakitleri ve duyuru ekranı.",
    category: "cami",
    image: "/images/gallery/cami-1.jpg",
  },
  {
    id: 9,
    title: "Showroom LED Video Wall",
    description: "Otomotiv showroomunda 20 m² indoor video wall.",
    category: "magaza",
    image: "/images/gallery/store-2.jpg",
  },
];
